v <- c( 3,7.3,5)
t <- c(9,4,2)
print("Addition:")
print(v+t)
print("Subtraction:")
print(v-t)
print("Multiplication:")
print(v*t)
print("Division:")
print(v/t)
print("Remainder:")
print(v%%t)
print("Integer Quotient:")
print(v%/%t)
print("Power function:")
print(v^t)
